// =============================================
//  PASA-TRAVELS — Static Data
// =============================================

export const TOURS = [
  {
    id: 1,
    title: 'Everest Base Camp Classic Trek',
    location: 'Everest Region',
    days: 14,
    maxGroup: 12,
    difficulty: 'hard',
    rating: 5.0,
    reviews: 128,
    price: 1299,
    badge: 'Best Seller',
    badgeColor: null,
    image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=600&auto=format&fit=crop',
  },
  {
    id: 2,
    title: 'Annapurna Circuit Adventure',
    location: 'Annapurna Region',
    days: 18,
    maxGroup: 10,
    difficulty: 'hard',
    rating: 4.9,
    reviews: 87,
    price: 1199,
    badge: 'Popular',
    badgeColor: 'var(--secondary)',
    image: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=600&auto=format&fit=crop',
  },
  {
    id: 3,
    title: 'Kathmandu Heritage & Culture',
    location: 'Kathmandu Valley',
    days: 5,
    maxGroup: 15,
    difficulty: 'easy',
    rating: 4.8,
    reviews: 203,
    price: 349,
    badge: null,
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=600&auto=format&fit=crop',
  },
  {
    id: 4,
    title: 'Pokhara Lakes & Paragliding',
    location: 'Pokhara',
    days: 4,
    maxGroup: 8,
    difficulty: 'easy',
    rating: 4.7,
    reviews: 64,
    price: 299,
    badge: 'New',
    badgeColor: '#22c55e',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=600&auto=format&fit=crop',
  },
  {
    id: 5,
    title: 'Langtang Valley Trek',
    location: 'Langtang Valley',
    days: 10,
    maxGroup: 12,
    difficulty: 'moderate',
    rating: 4.6,
    reviews: 45,
    price: 799,
    badge: null,
    image: 'https://images.unsplash.com/photo-1569091791842-7cfb64e04797?w=600&auto=format&fit=crop',
  },
  {
    id: 6,
    title: 'Upper Mustang Forbidden Kingdom',
    location: 'Upper Mustang',
    days: 16,
    maxGroup: 8,
    difficulty: 'moderate',
    rating: 4.9,
    reviews: 32,
    price: 2499,
    badge: 'Premium',
    badgeColor: '#9333ea',
    image: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=600&auto=format&fit=crop',
  },
  {
    id: 7,
    title: 'Chitwan Jungle Safari',
    location: 'Chitwan National Park',
    days: 3,
    maxGroup: 16,
    difficulty: 'easy',
    rating: 4.7,
    reviews: 89,
    price: 449,
    badge: null,
    image: 'https://images.unsplash.com/photo-1617195737496-bc30194e3a19?w=600&auto=format&fit=crop',
  },
  {
    id: 8,
    title: 'Gokyo Lakes Trek',
    location: 'Everest Region',
    days: 12,
    maxGroup: 12,
    difficulty: 'moderate',
    rating: 4.8,
    reviews: 53,
    price: 999,
    badge: null,
    image: 'https://images.unsplash.com/photo-1465778893808-9b3e4c12e741?w=600&auto=format&fit=crop',
  },
  {
    id: 9,
    title: 'Poon Hill Sunrise Trek',
    location: 'Annapurna Region',
    days: 7,
    maxGroup: 14,
    difficulty: 'moderate',
    rating: 4.5,
    reviews: 71,
    price: 599,
    badge: null,
    image: 'https://images.unsplash.com/photo-1494548162494-384bba4ab999?w=600&auto=format&fit=crop',
  },
  {
    id: 10,
    title: 'Manaslu Circuit Trek',
    location: 'Manaslu Region',
    days: 15,
    maxGroup: 10,
    difficulty: 'hard',
    rating: 5.0,
    reviews: 28,
    price: 1599,
    badge: 'Challenging',
    badgeColor: '#ef4444',
    image: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=600&auto=format&fit=crop',
  },
  {
    id: 11,
    title: 'Nagarkot Sunrise Day Tour',
    location: 'Kathmandu Valley',
    days: 2,
    maxGroup: 20,
    difficulty: 'easy',
    rating: 4.6,
    reviews: 142,
    price: 249,
    badge: null,
    image: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=600&auto=format&fit=crop',
  },
  {
    id: 12,
    title: 'Helambu Circuit Trek',
    location: 'Helambu Region',
    days: 9,
    maxGroup: 12,
    difficulty: 'moderate',
    rating: 4.8,
    reviews: 37,
    price: 899,
    badge: null,
    image: 'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=600&auto=format&fit=crop',
  },
];

export const GUIDES = [
  {
    id: 1,
    name: 'Rajan Thapa',
    role: 'Trekking & Mountaineering',
    languages: 'English · Hindi · Nepali',
    rating: 5.0,
    reviews: 94,
    experience: 12,
    trips: '320+',
    rate: '$85',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&auto=format&fit=crop',
  },
  {
    id: 2,
    name: 'Priya Sharma',
    role: 'Cultural & Heritage Tours',
    languages: 'English · French · Nepali',
    rating: 4.9,
    reviews: 76,
    experience: 8,
    trips: '210+',
    rate: '$75',
    image: 'https://images.unsplash.com/photo-1607746882042-944635dfe10e?w=400&auto=format&fit=crop',
  },
  {
    id: 3,
    name: 'Bishal Rai',
    role: 'High Altitude Expert',
    languages: 'English · German · Nepali',
    rating: 4.8,
    reviews: 58,
    experience: 15,
    trips: '450+',
    rate: '$95',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&auto=format&fit=crop',
  },
  {
    id: 4,
    name: 'Sunita Gurung',
    role: 'Wildlife & Nature Guide',
    languages: 'English · Spanish · Nepali',
    rating: 4.9,
    reviews: 112,
    experience: 10,
    trips: '380+',
    rate: '$80',
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&auto=format&fit=crop',
  },
  {
    id: 5,
    name: 'Kamal Shrestha',
    role: 'Annapurna Specialist',
    languages: 'English · Japanese · Nepali',
    rating: 4.8,
    reviews: 63,
    experience: 11,
    trips: '290+',
    rate: '$85',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop',
  },
  {
    id: 6,
    name: 'Laxmi Tamang',
    role: 'Adventure & Trekking',
    languages: 'English · Korean · Nepali',
    rating: 4.7,
    reviews: 49,
    experience: 7,
    trips: '185+',
    rate: '$70',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&auto=format&fit=crop',
  },
  {
    id: 7,
    name: 'Deepak Magar',
    role: 'EBC & Himalayan Treks',
    languages: 'English · Chinese · Nepali',
    rating: 5.0,
    reviews: 38,
    experience: 9,
    trips: '220+',
    rate: '$90',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&auto=format&fit=crop',
  },
  {
    id: 8,
    name: 'Anita Bhandari',
    role: 'Yoga & Wellness Retreats',
    languages: 'English · Italian · Nepali',
    rating: 4.9,
    reviews: 84,
    experience: 6,
    trips: '160+',
    rate: '$65',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&auto=format&fit=crop',
  },
];

export const DESTINATIONS = [
  {
    id: 1,
    name: 'Everest Region',
    badge: 'Highest Peak',
    badgeIcon: 'bi-snow',
    altitude: '5,364m Base Camp',
    tours: 12,
    image: 'https://images.unsplash.com/photo-1484910292437-025e5d13ce87?w=800&auto=format&fit=crop',
    description: 'Home to the world\'s highest mountain, the Everest region offers some of the most iconic trekking routes on Earth. The Everest Base Camp trek is a bucket-list adventure that takes you through Sherpa villages, ancient monasteries, and stunning glacial landscapes.',
    highlights: ['Everest Base Camp (5,364m)', 'Kala Patthar viewpoint', 'Namche Bazaar Sherpa market', 'Tengboche Monastery', 'Gokyo Lakes'],
    bestTime: 'March–May, Oct–Nov',
  },
  {
    id: 2,
    name: 'Annapurna',
    badge: 'Circuit Trek',
    badgeIcon: 'bi-compass',
    altitude: '5,416m Thorong La',
    tours: 9,
    image: 'https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=800&auto=format&fit=crop',
    description: 'The Annapurna Circuit is one of the world\'s classic treks, circling the Annapurna massif through diverse landscapes. From subtropical forests to high alpine terrain, crossing Thorong La Pass is a highlight of any Nepal adventure.',
    highlights: ['Thorong La Pass (5,416m)', 'Muktinath Temple', 'Tatopani hot springs', 'Poon Hill sunrise', 'Manang village'],
    bestTime: 'March–May, Oct–Nov',
  },
  {
    id: 3,
    name: 'Kathmandu Valley',
    badge: 'Cultural Capital',
    badgeIcon: 'bi-building-fill',
    altitude: '1,400m',
    tours: 8,
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop',
    description: 'A UNESCO World Heritage Site containing seven monument zones. Ancient temples sit beside buzzing streets in this vibrant city where Hindu and Buddhist cultures blend seamlessly.',
    highlights: ['Pashupatinath Temple', 'Boudhanath Stupa', 'Swayambhunath (Monkey Temple)', 'Patan Durbar Square', 'Bhaktapur'],
    bestTime: 'Year-round',
  },
  {
    id: 4,
    name: 'Pokhara',
    badge: 'Lake City',
    badgeIcon: 'bi-water',
    altitude: '822m',
    tours: 6,
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&auto=format&fit=crop',
    description: 'Nepal\'s tourism capital set against the dramatic backdrop of the Annapurna range. Phewa Lake reflects the mountains perfectly, and the city offers paragliding, boating, and the famous sunrise from Sarangkot.',
    highlights: ['Phewa Lake', 'Sarangkot sunrise', 'Paragliding', 'Davis Falls', 'Begnas Lake'],
    bestTime: 'October–May',
  },
  {
    id: 5,
    name: 'Langtang',
    badge: 'Valley of Glaciers',
    badgeIcon: 'bi-snow2',
    altitude: '3,430m Langtang Village',
    tours: 4,
    image: 'https://images.unsplash.com/photo-1569091791842-7cfb64e04797?w=800&auto=format&fit=crop',
    description: 'Close to Kathmandu yet surprisingly off the beaten track, Langtang Valley offers beautiful trekking through rhododendron forests, traditional Tamang villages, and alpine meadows.',
    highlights: ['Kyanjin Gompa', 'Tserko Ri viewpoint', 'Langtang Village', 'Glacier views', 'Cheese factory'],
    bestTime: 'March–May, Oct–Dec',
  },
  {
    id: 6,
    name: 'Upper Mustang',
    badge: 'Forbidden Kingdom',
    badgeIcon: 'bi-flag-fill',
    altitude: '3,840m Lo Manthang',
    tours: 3,
    image: 'https://images.unsplash.com/photo-1586348943529-beaae6c28db9?w=800&auto=format&fit=crop',
    description: 'The former Kingdom of Lo, opened to tourists only in 1992. Mustang\'s ancient Tibetan culture, cave monasteries, and dramatic desert landscape make it one of Nepal\'s most unique destinations.',
    highlights: ['Lo Manthang walled city', 'Chungsi cave monastery', 'Muktinath Temple', 'Tiji Festival', 'Ancient cave dwellings'],
    bestTime: 'May–October',
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    text: 'Rajan was an absolutely incredible guide. His knowledge of the trails and local culture made our Everest Base Camp trek unforgettable. We felt safe and well-informed throughout the 14 days.',
    name: 'Sarah Mitchell',
    country: 'United States',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop',
  },
  {
    id: 2,
    text: 'Booked the Kathmandu Heritage tour and it was worth every penny. Priya\'s storytelling brought every temple and palace to life. The booking process on PASA-TRAVELS was seamless too!',
    name: 'Marco Delgado',
    country: 'Italy',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop',
  },
  {
    id: 3,
    text: 'The Annapurna Circuit with Bishal was the adventure of a lifetime. Thorong La Pass at 5,416m — I never thought I\'d do it! The support team was excellent and food was surprisingly great.',
    name: 'Yuki Tanaka',
    country: 'Japan',
    rating: 5,
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop',
  },
];
